-- personal de la UAB

INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Aren','','Acnuta','Chirre','4455912',3,'1991-03-01','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Mikael','','Agreda','Herbas','3722371',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jose','Luis','Aguilar','Conde','7511893',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ivo','Alberto','Alabe','Perales','2311307',2,'1975-10-10','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lourdes','Sofia','Alanes','Terrazas','6461124',3,'1986-05-10','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Vladimir','','Alanoca','Espejo','6174669',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ivan','Ronny','Alcon','Andia','5920379',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Froilan','','Alcon','Sullcani','440526',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Patricia','','Alderete','Fernandez','6329245',4,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Cristhian','John','Alvarez','Zaldua','O914312988',10,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lizeth','','Alvarez','Zerda','4451395',3,'1978-12-05','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Celia','Maria','Apaza','Narvacia','4479470',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Juan','','Arhuata','Luna','5223872',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Madelein','','Arias','Carrasco','8038724',3,'1992-08-06','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Gisela','','Arivilea','Medina','4317206',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lizet','Mery','Arratia','Quispe','4908172',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Dunia','','Arze','Suheiro','6509435',3,'1987-07-10','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Julieta','','Ascarraga','Jaldin','5161148',3,'1979-07-02','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Danae','','Asturizaga','Camacho','3754558',3,'1987-12-06','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Judith','Mabel','Ayala','Choque','4314859',2,'1974-03-10','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Sonia','Miriam','Ayala','Condori','2142827',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ivan','Nelson','Ayala','Santos','2372433',2,'1969-06-11','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Sonia','Alicia','Barriuso','De la parra','986397',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ovidio','Moises','Becerra','Rodas','4580520',4,'1977-10-05','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lidia','Maura','Bernal','Vargas','3078271',1,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Irene','Carmen','Calderon','Copa','4478383',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ever','Samuel','Calle','Mamani','5239536',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Hugo','','Campos','Bautista','4040896',1,'1978-01-04','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Liliana','Veronica','Canqui','Cama','3422659',2,'1970-06-11','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Mery','','Carrasco','','3613475',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Mario','','Carrasco','Quiroz','4380799',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Clara','Evelin','Carvajal','Limachi','4843942',2,'1979-06-04','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Boris','','Carvajal','Rojas','7882823',3,'1988-04-06','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Rolando','Delmer','Castillo','Limachi','2533041',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Xavier','Americo','Cespedes','Teran','3620666',3,'1974-01-07','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Willy','Luis','Chambilla','Silva','2581565',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jacob','Angel','Charcas','Canaviri','2448700',2,'1962-04-08','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Martin','Edwin','Charcas','Canaviri','2613433',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Sandra','Mischel','Charcas','Enriquez','6431790',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Henry','Omar','Chavarria','Ramirez','3622565',3,'1969-10-09','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Marco','Antonio','Chavarria','Ramirez','4461205',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Milda','Mery','Chipana','Quispe','6546437',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Roxana','','Chipana','Viadez','4287848',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ruben','','Choque','Mamani','4245910',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Juan','Wilfredo','Choque','Medrano','2642110',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Guimer','','Choque','Nina','7975990',3,'1989-03-05','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Juan','Carlos','Choque','Nina','7988892',3,'1985-08-01','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Wladimir','','Chuquimia','Rivero','4414778',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Hernan','Eustaquio','Chuquimia','Tancara','2600568',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Milton','Jose','Chuquimia','Zabala','3000525',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Mario','Rolando','Chura','Ortiz','4377774',2,'1976-03-07','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ramiro','','Claros','Churqui','3695745',9,'1968-12-11','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lorgio','Divar','Colque','Choque','6187686',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Celia','','Colque','Flores','5311727',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Yhanet','','Colque','Mamani','5480721',2,'1982-03-10','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Virginia','','Condori','Apulaca','5948349',2,'1981-05-04','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Alicia','Margot','Contreras','Jara','6520153',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ludmila','Silvia','Cruz','Patty','5223889',3,'1980-07-01','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Karla','Alejandra','Cruz','Soto','6466484',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Eloyna','Lizeht','Cuiza','Morales','3054569',1,'1967-03-01','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Fabiola','Liz','Delgado','Mamani','6446646',3,'1989-08-04','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Nidia','Esther','Duran','Burgoa','6477658',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Eduardo','','Enriquez','Aramayo','1022919',8,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Mary','Dunia','Escobar','Arias','4529153',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Carla','Fabiana','Espada','Rossell','5303458',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Luis','Evelio','Estrada','Estrada','2068980',2,'1958-11-05','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Claudio','Fidel','Flores','Colquehuanca','4311615',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Delfin','Ivan','Flores','Colquehuanca','4777161',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Janeth','','Flores','Quiroz','6234456',4,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Cristhian','Fabian','Garcia','IbaÑez','8694083',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Dolly','Gabriela','Gardeazabal','Guzman','4083588',8,'1978-07-06','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lucy','Marlenny','Garnica','AcuÑa','8207041',4,'1992-02-01','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Freddy','','Gomez','Mayta','5471063',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Nielsen','Salomon','Gonzales','Alarcon','3476260',2,'1971-07-08','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Rodolfo','','Guarachi','Ramos','4881536',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jorge','Herbert','Guzman','Sandoval','3046142',1,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Benigna','','Herbas','Panozo','3030026',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Carlos','Alejandro','Heredia','Flores','4532920',3,'1981-06-12','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Zonia','Lidia','Huamani','Tello','6416523',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Rolando','Alex','Huanca','Gomez','4070515',1,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Adela','','Huanca','Paco','2584324',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ivan','Jhonny','Huayta','Lucana','3972503',9,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Maria','Magdalena','Hurtado','Calle','4383839',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jacqueline','','Illanes','Manrique','2714703',2,'1965-05-01','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lucien','Edith','Iquiza','Ramirez','3519536',1,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Emilia','','Jaldin','','3754662',3,'1973-01-12','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Felicia','','Justiniano','Moreno','3925671',4,'1974-03-05','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lorna rosa','Elizabeth','Kreidler','Guillaux','1980843',4,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Luz','Marleny','Leon','Jauregui','4798574',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Guido','Wilmer','Limari','Huanca','6986755',2,'1989-11-03','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Guillermo','','Lizarraga','Barba','393080',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Melvy','Ivette','Llusco','Narvaez','4741259',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Paula','Milenca','Llusco','Ramos','3356930',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Marcelino','','Lopez','Mamani','2639898',2,'1965-02-01','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jannette','Marga','Loza','Sosa','6012947',2,'1983-10-02','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Sonia','','Lucas','Calani','2784057',1,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jenny','Judith','Maita','Montevilla','3570618',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Luis','Rodrigo','Maldonado','Callao','6480302',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Veronica','','Mamani','Arnez','3447321',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Leticia','','Mamani','Choque','6888773',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Esperanza','Juana','Mamani','Mamani','3416556',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Wassia','','Mamani','Mamani','6812832',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Abraham','','Mamani','Veliz','4477199',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Roberto','Carlos','Marca','Tinta','5045150',5,'1985-04-07','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Galo','','Medina','PeÑa','2889683',3,'1963-11-03','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Martha','Veronica','Mejia','Navia','3755372',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Dina','Gladys','Mena','Sarco','2554403',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Gil','','Mezza','Avila','1076173',8,'1962-01-09','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Sandro','','Mita','Carrera','2377397',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Franz','','Mita','Machaca','5398683',4,'1977-04-10','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Luisa','','Mita','Tola','3147023',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jaime','','MontaÑo','Gallardo','5900129',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Gladys','','Morales','Cuellar','3099863',1,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Rosaura','Miriam','Morales','PaÑuni','3378182',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Obed','Rafael','Morante','Quisbert','6494523',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jenny','Isabel','Nogales','Copa','4443242',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Carlos','Patricio','Olivares','Rodriguez','O3781057',11,'1972-07-01','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Raquel','','Orellana','Guevara','4728026',4,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Adriana','Rocio','Ortiz','Aparicio','6540944',3,'1988-03-10','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Yenny','Bonny','Ortiz','Vasquez','3588853',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lizeth','','Paco','Mena','4314250',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Pablo','Elias','Paco','Poma','4837988',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Yojan','David','Paco','Rodriguez','5941869',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jose','Maria','Pardo','Brito','6355776',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Blanca','Eliana','Patzi','Flores','3358042',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lizeth','Angelica','Paz','Callisaya','6789797',2,'1990-12-05','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Patricia','Lenny','Peredo','Davalos','4506705',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lizeth','','Perez','Mamani','6560475',9,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Evert','Erwin','Perez','Morales','5189904',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Victor','Hugo','Perez','Rojas','4845594',2,'1979-06-05','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Heber','','Pinheiro','Salazar','3144281',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Aurora','Elizabeth','Pocoaca','Saenz','2208172',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Severo','Victor','Quino','Arroyo','8053329',3,'1968-08-11','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Wilson','','Quiroga','Saavedra','5190547',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Eloy','Armando','Quispe','Huanca','3439614',2,'1971-01-12','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Eunice','','Quispe','UreÑa','5938278',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Elida','','Rivero','Cosio','928931',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Daniel','Porfirio','Rodriguez','Chacon','3403957',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Silvia','','Rodriguez','Herrera','6187310',2,'1987-05-02','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Marisol','','Rodriguez','Valencia','6481747',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ingrid','Ximena','Rojas','Malfert','2229114',2,'1963-06-03','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lisa','Vibiana','Rojas','Ponce','3725442',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Victor','Fernando','Rojas','Quispe','6896630',2,'1988-01-12','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jaime','Arturo','Ruilova','Torres','2150220',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jhoann','Evelin','Saavedra','Mercado','8987919',4,'1993-04-12','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Miguel','Angel','Salomon','Mendez','762344',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Grover','Enrrique','Sanchez','Alberto','3332231',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jose','Luis','Santa cruz','Ruiz','1538079',4,'1953-07-04','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Eduardo','','Saravia','Achu','6792714',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Nancy','','Sarzuri','Marin','3362995',2,'1968-07-11','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Shirley','Claudia','Siles','Quintanilla','4458533',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Lendy','Marioly','Simon','Melendres','7285301',1,'1992-04-06','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Marcia','','Sinko','Yapu','4483908',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Clotilde','Elizabeth','Solis','Gutierrez','3022878',3,'1964-12-07','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Oscar','Rafael','Suarez','Hinojoza','4530066',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Freddy','Efrain','Tancara','Villca','4042130',1,'1979-08-08','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Marcia','Rocio','Tapia','Alvarez','3501035',1,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Shirlyn','Dania','Tapia','Cruz','3506485',1,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Estefania','','Tarqui','Valle','4462224',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Ramiro','','Teran','Encinas','4411368',3,'1976-11-04','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Juana','','Terrazas','Terrazas','8236831',4,'1989-05-27','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Oscar','Jose','Tola','Huarachi','3091501',1,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Angelica','','Ucharico','Apaza','6010891',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Jose','Manuel','Ugarteche','Herrera','3270676',4,'1972-08-04','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Wilmer','','Uraquina','Garcia','5262143',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Sara','Milka','Valdez','TacanÁ','5963273',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Rolando','Elmer','Vallejos','Aranibar','2900073',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Sandra','Virginia','Vargas','Fernandez','5313631',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('David','','Vargas','Orellana','3822446',4,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Elias','Francisco','Vargas','Valdez','5037697',5,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Claudia','','Veizaga','Rios','4528162',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Noelene','','Ventura','Canaviri','7863094',3,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Nohemi','','Ventura','Canaviri','5720811',1,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Miguel','','Vera','Colque','3551744',1,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Karina','','Villarroel','Colque','4021831',1,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Roman','','Villarroel','Meruvia','4482778',3,'1979-06-07','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Elizabeth','','Villca','Callizaya','8444687',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('David','Gerson','Villca','Fernandez','6408844',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Samuel','','Vino','Vino','5473579',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Javier','','Viscarra','Carrasco','5938122',3,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Joel','Ramiro','Yugar','Mier','3506232',1,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Max','Abel','Yugar','Mier','3097586-1M',1,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Christian','','Yujra','Castillo','8361272',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Sergio','Gustavo','Zabaleta','Susara','3422315',2,'1973-03-07','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Alvaro','Alberto','Zacarias','Mamani','6872318',2,'1969-12-31','M',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Dorti','Eliana','Zapata','Palli','4797289',2,'1969-12-31','F',1);
INSERT INTO persona(primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,CI,idLugarExpedicion,fechaNacimiento,sexo,idEstadoCivil) VALUES ('Luis','','Zegarra','Mamani','2417228',2,'1969-12-31','M',1);

-- tipodepartamentocontacto
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('UNIÓN BOLIVIANA');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('IATEC');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('SPA');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('UAB');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('ADRA');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('CNT');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('EDICIONES NUEVO TIEMPO');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('MBO');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('MBC');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('MOB');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('SERVICIOS (SOLO UB)');
INSERT INTO tipodepartamentocontacto(nombre) VALUES ('HOTELES');

-- departamento contacto
INSERT INTO departamentocontacto(idTipoDepartamentoContacto,nombre,direccion,email,direccionWeb,casillaPostal) VALUES (1,'UNIÓN BOLIVIANA (UB)','Av. Simón López 391 – B° Cala Cala – Cochabamba','','www.ub.adventistas.org','3535');
INSERT INTO departamentocontacto(idTipoDepartamentoContacto,nombre,direccion,email,direccionWeb,casillaPostal) VALUES (2,'INSTITUTO ADVENTISTA DE TECNOLOGÍA (IATec)','Av. Simón Patiño Km. 1, s/n – Pairumani, Vinto','','','');
INSERT INTO departamentocontacto(idTipoDepartamentoContacto,nombre,direccion,email,direccionWeb,casillaPostal) VALUES (3,'SERVICIO DE PUBLICACIONES ADVENTISTA (SPA)','Av. Juan de la Rosa esq. Diómedes de Pereira s/n, zona Sarco – Cochabamba','','www.adventistas.org.bo','3525');
INSERT INTO departamentocontacto(idTipoDepartamentoContacto,nombre,direccion,email,direccionWeb,casillaPostal) VALUES (4,'UNIVERSIDAD ADVENTISTA DE BOLIVIA (UAB)','Av. Simón Patiño Km. 1, s/n – Pairumani, Vinto','info@uab.edu.bo','www.uab.edu.bo','');

-- FAX departamento
INSERT INTO fax(idDepartamentoContacto,numero,prefijo) VALUES (1,'441-3485','591 - 4');
INSERT INTO fax(idDepartamentoContacto,numero,prefijo) VALUES (4,'426-3336','4');

-- TelefonoDepartamento
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (1,'Fijo','411-5753','591 - 4');
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (1,'Fijo','411-7388','591 - 4');
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (1,'Fijo','441-3481','591 - 4');
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (1,'Fijo','441-3482','591 - 4');
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (1,'Fijo','441-3487','591 - 4');
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (3,'Fijo','450-6583 ','591 - 4');
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (3,'Fijo','451-3500','591 - 4');
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (4,'Fijo','426-3330','591 - 4');
INSERT INTO telefonoDepartamento(idDepartamentoContacto,tipoTelefono,numero,prefijo) VALUES (4,'Fijo','426-3331','591 - 4');

-- responsabilidad
INSERT INTO responsabilidad(nombre) VALUES ('AFAM - MINISTERIO DE LA MUJER');
INSERT INTO responsabilidad(nombre) VALUES ('ALMACÉN');
INSERT INTO responsabilidad(nombre) VALUES ('ALMACÉN SPA - MBC');
INSERT INTO responsabilidad(nombre) VALUES ('ALMACENES MBO');
INSERT INTO responsabilidad(nombre) VALUES ('ANALISTA DE TESORERÍA DE IGLESIAS');
INSERT INTO responsabilidad(nombre) VALUES ('ANALISTA REMESAS ');
INSERT INTO responsabilidad(nombre) VALUES ('ARQUITECTO');
INSERT INTO responsabilidad(nombre) VALUES ('ASESOR JURÍDICO, LIBERTAD RELIGIOSA');
INSERT INTO responsabilidad(nombre) VALUES ('ASESOR LEGAL');
INSERT INTO responsabilidad(nombre) VALUES ('ASESORA LEGAL MOB');
INSERT INTO responsabilidad(nombre) VALUES ('ASESORA PEDAGÓGICA ASEA');
INSERT INTO responsabilidad(nombre) VALUES ('ASESORÍA LEGAL');
INSERT INTO responsabilidad(nombre) VALUES ('ASIST. AUDITORÍA ');
INSERT INTO responsabilidad(nombre) VALUES ('ASIST. FINANCIERO Y CAPELLÁN');
INSERT INTO responsabilidad(nombre) VALUES ('ASIST. LEGALES ASEA');
INSERT INTO responsabilidad(nombre) VALUES ('ASIST. VENTAS - SRIA. PUBL.');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE DEPARTAMENTO LEGAL');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE ALMACÉN SPA - MBC');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE BIBLIOTECA');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE COCHABAMBA CENTRAL');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE COCHABAMBA SUR ');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE COLPORTORES');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE CONTABLE ASEA');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE DE COMUNICACIONES');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE DE CONTABILIDAD');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE DE PUBLICACIONES');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE DE SECRETARÍA IGLESIAS');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE FINANCIERO');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE LEGAL');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE SECRETARIA GENERAL');
INSERT INTO responsabilidad(nombre) VALUES ('ASISTENTE VALLE ALTO');
INSERT INTO responsabilidad(nombre) VALUES ('ASOCIACIÓN MINISTERIAL, MAYORDOMÍA CRISTIANA');
INSERT INTO responsabilidad(nombre) VALUES ('ASOCIACIÓN MINISTERIAL Y COMUNICACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('ATENCIÓN LIBRERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('AUDITOR - GESTOR DE REMESAS');
INSERT INTO responsabilidad(nombre) VALUES ('AUDITOR INTERNO');
INSERT INTO responsabilidad(nombre) VALUES ('AUDITOR MOB');
INSERT INTO responsabilidad(nombre) VALUES ('AUXILIAR');
INSERT INTO responsabilidad(nombre) VALUES ('AUXILIAR CONTABLE');
INSERT INTO responsabilidad(nombre) VALUES ('AUXILIAR DE PLANTA');
INSERT INTO responsabilidad(nombre) VALUES ('AUXILIAR DE SECRETARIA GENERAL');
INSERT INTO responsabilidad(nombre) VALUES ('AYUDANTE - LAHUACHACA - PATIHIPE');
INSERT INTO responsabilidad(nombre) VALUES ('AYUDANTE - PATACAMAYA "B" - CURAHUARA');
INSERT INTO responsabilidad(nombre) VALUES ('AYUDANTE DE JARDÍNES');
INSERT INTO responsabilidad(nombre) VALUES ('BEDELIA');
INSERT INTO responsabilidad(nombre) VALUES ('CAJA');
INSERT INTO responsabilidad(nombre) VALUES ('CAJERO(A)');
INSERT INTO responsabilidad(nombre) VALUES ('CAJERO(A) MOB');
INSERT INTO responsabilidad(nombre) VALUES ('CAPELLÁN');
INSERT INTO responsabilidad(nombre) VALUES ('CAPELLÁN EDUCACIÓN – SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('CAPELLÁN UEAB SECUNDARIA');
INSERT INTO responsabilidad(nombre) VALUES ('CAPELLÁN-FINANCIERO');
INSERT INTO responsabilidad(nombre) VALUES ('CHIQUITANÍA');
INSERT INTO responsabilidad(nombre) VALUES ('COMEDOR');
INSERT INTO responsabilidad(nombre) VALUES ('COMUNICACIONES RNT');
INSERT INTO responsabilidad(nombre) VALUES ('CONAVI ');
INSERT INTO responsabilidad(nombre) VALUES ('CONQUISTADORES Y AVENTUREROS, JA, MÚSICA');
INSERT INTO responsabilidad(nombre) VALUES ('CONSERJE');
INSERT INTO responsabilidad(nombre) VALUES ('CONSERJE - LIMPIEZA');
INSERT INTO responsabilidad(nombre) VALUES ('CONSERJE CARANAVI');
INSERT INTO responsabilidad(nombre) VALUES ('CONSTRUCCIÓN ');
INSERT INTO responsabilidad(nombre) VALUES ('CONTADOR ASEA');
INSERT INTO responsabilidad(nombre) VALUES ('CONTADOR ASEA-MBC');
INSERT INTO responsabilidad(nombre) VALUES ('CONTADOR DE TESORERÍA DE IGLESIAS');
INSERT INTO responsabilidad(nombre) VALUES ('CONTADOR MOB');
INSERT INTO responsabilidad(nombre) VALUES ('CONTADOR(A)');
INSERT INTO responsabilidad(nombre) VALUES ('CONTADOR(A) REGIONAL');
INSERT INTO responsabilidad(nombre) VALUES ('COORDINADOR(A) ACADÉMICO(A)');
INSERT INTO responsabilidad(nombre) VALUES ('COORDINADOR(A) MARKETING Y CREA');
INSERT INTO responsabilidad(nombre) VALUES ('COORDINADOR(A) PEDAGÓGICO(A)');
INSERT INTO responsabilidad(nombre) VALUES ('COORDINADOR(A) ACADÉMICO(A) TURNO MAÑANA');
INSERT INTO responsabilidad(nombre) VALUES ('COORDINADOR(A) ACADÉMICO(A) TURNO TARDE');
INSERT INTO responsabilidad(nombre) VALUES ('DECANO(A) FACULTAD DE CIENCIAS DE SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('DECANO(A) FACULTAD DE EDUCACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('DECANO(A) FCEA');
INSERT INTO responsabilidad(nombre) VALUES ('DECANO(A) INGENIERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('DECANO(A) TEOLOGÍA');
INSERT INTO responsabilidad(nombre) VALUES ('DEPARTAMENTAL ASEA-MBC');
INSERT INTO responsabilidad(nombre) VALUES ('DEPARTAMENTO DE INVESTIGACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('DIR. PAC E INVESTIGACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('DIR. TÉCNICO TV Y RADIO');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR ASOCIADO PUBLICACIONES');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR BIBLIOTECA');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR DE BIENESTAR ESTUDIANTIL');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR DE ESCUELA BÍBLICA');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR DPTO PUBLICACIONES ');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR FINANCIERO');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR GENERAL');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR IDEC');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR INSTITUTO DE MÚSICA');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR TV Y RADIO');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR UEAB');
INSERT INTO responsabilidad(nombre) VALUES ('DIRECTOR(A)');
INSERT INTO responsabilidad(nombre) VALUES ('DISEÑADOR(A)');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL INQUISIVI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL 12 DE OCTUBRE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL 16 DE JULIO');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL 21 DE SEPTIEMBRE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ACHACACHI ');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ALTIPLANO NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ALTO BENI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL AMAZONÍA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL APOLO - ESCOMA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL BELLO HORIZONTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL CARANAVI "A"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL CARANAVI "B"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL CARANAVI "B"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL CARANAVI "C"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL CEAB');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL CENTRAL LA PAZ');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL CHARAPAQUI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL CHULUMANI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COBIJA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COCHABAMBA CENTRAL');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COCHABAMBA ESTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COCHABAMBA NORESTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COCHABAMBA NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COCHABAMBA PROGRESO');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COCHABAMBA SUR');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COROICO');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL COSMOS');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL DE NUEVOS HORIZONTES');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL DE ROSARIO');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL EL LAGO');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ENTRE RÍOS');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL GALINDO NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL GUAYARAMERÍN');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL HUAYNA POTOSÍ');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL I.A.L.A.');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ILLIMANI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL IVIRGARZAMA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL KUPINI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL KUPINI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LA ASUNTA "A"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LA ASUNTA "B"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LA ASUNTA "C"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LA HERMOSA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LA HERMOSA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LA PORTADA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LAHUACHACA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LAS FRONTERAS');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LAS MERCEDES');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LAZARTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LLALLAGUA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LOMA LINDA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LOS ANDES');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL LOS ANDES (AYUDANTE)');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL MIRAFLORES');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL MONTERO');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL NORTE LA PAZ');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL OBRAJES');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ORURO CENTRAL');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ORURO ESTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ORURO NORESTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ORURO NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL ORURO SUR');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL PACAJES');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL PAIRUMANI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL PAMPAHASI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL PATACAMAYA "A"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL PATACAMAYA "B"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL PLAN 3000');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL POTOSÍ/LOS CINTIS');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL POTOSÍ/UYUNI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL PUERTO SUAREZ');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL PUESTO FERNÁNDEZ');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL QUILLACOLLO NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL QUILLACOLLO SUR');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL RÍO SECO "A"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL RURRENABAQUE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SACABA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SAN BORJA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SC-CENTRAL');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SENKATA "A"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SENKATA "B"');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SOPOCACHI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SUCRE CENTRAL');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SUCRE NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SUMUMPAYA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL SUR LA PAZ');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL TRINIDAD SUROESTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL TUPIZA/VILLAZON');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL UAB');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL V.REMEDIOS-COLLANA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VALLE ALTO');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VIACHA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA ADELA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA BALLIVÍAN');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA COPACABANA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA COPACABANA (AYUDANTE)');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA DOLORES');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA FÁTIMA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA MEXICO');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA SAN SALVADOR');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA TEJADA');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VILLA TUNARI');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VINTO NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL VINTO SUR');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL WARNES');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL YACUIBA “A”');
INSERT INTO responsabilidad(nombre) VALUES ('DISTRITAL YAPACANÍ');
INSERT INTO responsabilidad(nombre) VALUES ('DOCENTE FACULTAD DE TEOLOGÍA');
INSERT INTO responsabilidad(nombre) VALUES ('DOCENTE FACULTAD DE CS. DE LA EDUCACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('DOCENTE FACULTAD DE CS. SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('DOCENTE FCEA');
INSERT INTO responsabilidad(nombre) VALUES ('DOCENTE FACULTAD DE INGENIERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('EDITOR-VIDEO');
INSERT INTO responsabilidad(nombre) VALUES ('EDUCACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('EDUCACIÓN, COMUNICACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('EDUCACIÓN, LIBERTAD RELIGIOSA Y MÚSICA');
INSERT INTO responsabilidad(nombre) VALUES ('EDUCACIÓN, SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADA ALMACEN');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADA DE LECHERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADA SERVICIO LIMPIEZA');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADA VENTAS SPA');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADO ALMACENES CAMARGO');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADO ALMACENES EL ALTO');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADO CAMPUS DEPORTIVOS');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADO DE CARPINTERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADO DE INVENTARIOS SPA');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADO DE PLOMERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('ENCARGADO DE SONIDO Y PANADERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('EVANGELISMO - ESCUELA SABÁTICA - MINISTERIO PERSONAL');
INSERT INTO responsabilidad(nombre) VALUES ('EVANGELISMO, MIP-ES, ASA');
INSERT INTO responsabilidad(nombre) VALUES ('FINANCIERO(A)');
INSERT INTO responsabilidad(nombre) VALUES ('FINANCIERO/CAPE/PSICOPED.');
INSERT INTO responsabilidad(nombre) VALUES ('GERENTE FINANCIERO');
INSERT INTO responsabilidad(nombre) VALUES ('GERENTE T.I.');
INSERT INTO responsabilidad(nombre) VALUES ('GESTIÓN DEL TALENTO HUMANO');
INSERT INTO responsabilidad(nombre) VALUES ('GESTOR REMESAS');
INSERT INTO responsabilidad(nombre) VALUES ('GUARAYOS');
INSERT INTO responsabilidad(nombre) VALUES ('GUAYARAMERÍN');
INSERT INTO responsabilidad(nombre) VALUES ('INSA ARCHIVOS');
INSERT INTO responsabilidad(nombre) VALUES ('INSTRUCTOR BÍBLICO');
INSERT INTO responsabilidad(nombre) VALUES ('JARDINERO');
INSERT INTO responsabilidad(nombre) VALUES ('JEFE DE SEGURIDAD Y VIGILANCIA');
INSERT INTO responsabilidad(nombre) VALUES ('JEFE DE ALMACENES');
INSERT INTO responsabilidad(nombre) VALUES ('JEFE DE FINANZAS ALUMNOS');
INSERT INTO responsabilidad(nombre) VALUES ('JEFE DE JARDÍNES');
INSERT INTO responsabilidad(nombre) VALUES ('JEFE DE MANTENIMEINTO');
INSERT INTO responsabilidad(nombre) VALUES ('JEFE DE PRODUCCIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('LIBRERÍA SPA - MBC');
INSERT INTO responsabilidad(nombre) VALUES ('LIMPIEZA');
INSERT INTO responsabilidad(nombre) VALUES ('LOCUTOR(A)');
INSERT INTO responsabilidad(nombre) VALUES ('LOGISTICA -SERV ALIMENTACION');
INSERT INTO responsabilidad(nombre) VALUES ('MAMORÉ');
INSERT INTO responsabilidad(nombre) VALUES ('MANTENIMIENTO ');
INSERT INTO responsabilidad(nombre) VALUES ('MARKETING');
INSERT INTO responsabilidad(nombre) VALUES ('MC-SALUD – AM - HF');
INSERT INTO responsabilidad(nombre) VALUES ('MENSAJERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('MIN. PERSONAL, EE.SS, EVANGELISMO, ASA');
INSERT INTO responsabilidad(nombre) VALUES ('MINISTERIO DE LA MUJER - AFAM');
INSERT INTO responsabilidad(nombre) VALUES ('MINISTERIO DE PUBLICACIONES Y SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('MINISTERIO DEL NIÑO Y ADOLESCENTE');
INSERT INTO responsabilidad(nombre) VALUES ('MINISTERIO JOVEN - MÚSICA - COMUNICACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('MINISTERIO JOVEN - MÚSICA - HOGAR Y FAMILIA');
INSERT INTO responsabilidad(nombre) VALUES ('MINISTERIO JOVEN Y MIN. DE LA FAMILIA');
INSERT INTO responsabilidad(nombre) VALUES ('MIPES - ESC. SAB. - EV. - ASA');
INSERT INTO responsabilidad(nombre) VALUES ('MIPES – EVANGELISMO-ASA');
INSERT INTO responsabilidad(nombre) VALUES ('MJ-MA-MC-MÚSICA – MG');
INSERT INTO responsabilidad(nombre) VALUES ('MM, AFAM ');
INSERT INTO responsabilidad(nombre) VALUES ('MINISTERIO DE LA MUJER - MINISTERIO DEL NIÑO Y ADOLESCENTE');
INSERT INTO responsabilidad(nombre) VALUES ('MONTERO CENTRAL');
INSERT INTO responsabilidad(nombre) VALUES ('MONTERO NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('OPERADOR DE GUILLOTINA');
INSERT INTO responsabilidad(nombre) VALUES ('PASTOR DISTRITAL');
INSERT INTO responsabilidad(nombre) VALUES ('PERIODISTA');
INSERT INTO responsabilidad(nombre) VALUES ('PERSONAL DE INFORMÁTICA');
INSERT INTO responsabilidad(nombre) VALUES ('PERSONAL DE SEGURIDAD');
INSERT INTO responsabilidad(nombre) VALUES ('PERSONAL SEGURIDAD Y VIGILANCIA');
INSERT INTO responsabilidad(nombre) VALUES ('PIRAÍ');
INSERT INTO responsabilidad(nombre) VALUES ('PRECEPTOR HOGAR DE VARONES');
INSERT INTO responsabilidad(nombre) VALUES ('PRECEPTORA SEÑORITAS');
INSERT INTO responsabilidad(nombre) VALUES ('PRENSISTA');
INSERT INTO responsabilidad(nombre) VALUES ('PRESIDENTE');
INSERT INTO responsabilidad(nombre) VALUES ('PRESIDENTE - LIBERTAD RELIGIOSA');
INSERT INTO responsabilidad(nombre) VALUES ('PRESIDENTE, TESTAMENTO Y LEGADOS');
INSERT INTO responsabilidad(nombre) VALUES ('PROFESOR DE BIBLIA');
INSERT INTO responsabilidad(nombre) VALUES ('PROGRAMADOR');
INSERT INTO responsabilidad(nombre) VALUES ('PSICOPEDAGOGO(A)');
INSERT INTO responsabilidad(nombre) VALUES ('PUBLICACIONES - ESPÍRITU PROFECÍA - SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('PUBLICACIONES - SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('PUERTO SUÁREZ');
INSERT INTO responsabilidad(nombre) VALUES ('PUESTO FERNÁNDEZ');
INSERT INTO responsabilidad(nombre) VALUES ('RECEPCIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('RECEPCIÓN - JA');
INSERT INTO responsabilidad(nombre) VALUES ('RECEPCIÓN, SECRETARIA CONTABILIDAD');
INSERT INTO responsabilidad(nombre) VALUES ('RECEPCIONISTA');
INSERT INTO responsabilidad(nombre) VALUES ('RECEPCIONISTA Y DIGITADORA DE BAUTISMOS');
INSERT INTO responsabilidad(nombre) VALUES ('RECTOR');
INSERT INTO responsabilidad(nombre) VALUES ('RELACIONES PÚBLICAS Y VENTAS');
INSERT INTO responsabilidad(nombre) VALUES ('RESPONSABLE CONSTRUCCIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('RESPONSABLE LIMPIEZA');
INSERT INTO responsabilidad(nombre) VALUES ('RESPONSABLE REDES');
INSERT INTO responsabilidad(nombre) VALUES ('RIBERALTA');
INSERT INTO responsabilidad(nombre) VALUES ('RIO SECO "B"');
INSERT INTO responsabilidad(nombre) VALUES ('SAMAIPATA');
INSERT INTO responsabilidad(nombre) VALUES ('SAN JULIÁN');
INSERT INTO responsabilidad(nombre) VALUES ('SANTA FE');
INSERT INTO responsabilidad(nombre) VALUES ('SC - 4 DE NOVIEMBRE');
INSERT INTO responsabilidad(nombre) VALUES ('SC - ARROYITO');
INSERT INTO responsabilidad(nombre) VALUES ('SC - AVAROA');
INSERT INTO responsabilidad(nombre) VALUES ('SC - BARRIO LINDO');
INSERT INTO responsabilidad(nombre) VALUES ('SC - CENTRAL');
INSERT INTO responsabilidad(nombre) VALUES ('SC - HAMACAS');
INSERT INTO responsabilidad(nombre) VALUES ('SC - HAMACAS - ASOCIADO');
INSERT INTO responsabilidad(nombre) VALUES ('SC - LA COLORADA');
INSERT INTO responsabilidad(nombre) VALUES ('SC – LA GUARDIA');
INSERT INTO responsabilidad(nombre) VALUES ('SC - NORESTE');
INSERT INTO responsabilidad(nombre) VALUES ('SC - NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('SC - NUEVO PALMAR');
INSERT INTO responsabilidad(nombre) VALUES ('SC - PARI');
INSERT INTO responsabilidad(nombre) VALUES ('SC - PAURITO');
INSERT INTO responsabilidad(nombre) VALUES ('SC - PLAN 3000');
INSERT INTO responsabilidad(nombre) VALUES ('SC - SOBERANIA');
INSERT INTO responsabilidad(nombre) VALUES ('SC - SUR');
INSERT INTO responsabilidad(nombre) VALUES ('SC - SUROESTE');
INSERT INTO responsabilidad(nombre) VALUES ('SC - V. 1º DE MAYO');
INSERT INTO responsabilidad(nombre) VALUES ('SEC. MIN. JOVEN - COM. -M. NIÑO,ADOLESC.');
INSERT INTO responsabilidad(nombre) VALUES ('SEC. MIPES - EVANGELISMO-AFAM,MM');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA MIPES-PUBLICACIONES-SALUD-MN Y MA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA ACAD. FACULTAD CS. SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA ACADÉMICA EDUCACIÓN ');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARÍA ACMS');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA ADMINISTRACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA ADMINISTRACIÓN-ASOC. MIN.');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA ASEA ');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA BIENESTAR ESTUDIANTIL');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA CS. DE LA SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA DEPARTAMENTOS ');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA EDUCACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARÍA ESCUELA BÍBLICA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA EVANGELISMO,MIP-ES, CONQUIST.AVENT.,JA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA FAC. INGENIERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA FACULTAD DE CS. ECONÓMICAS');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA FACULTAD DE CS. EDUCACIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA FACULTAD TEOLOGÍA ');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA GENERAL');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARÍA IGLESIAS ACMS');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA MAYORDOMÍA-ASOC. MIN.-MM Y AFAM');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA PUBLICACIONES, RECEPCIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA PUBLICACIONES–AFAM-MM–MN Y MA–MAYORDOMÍA–SALUD');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIA RECEPCIONISTA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIO ACAD. TEOLOGÍA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIO ACADÉMICO FCEA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIO ACADÉMICO INGENIERÍA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIO EJECUTIVO');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIO EJECUTIVO - MIN. DE LA FAMILIA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIO EJECUTIVO Y MAYORDOMÍA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIO MINISTERIAL - MAYORDOMÍA - ASA');
INSERT INTO responsabilidad(nombre) VALUES ('SECRETARIO, MINISTERIO DE LA FAMILIA');
INSERT INTO responsabilidad(nombre) VALUES ('SERVICIOS - POMERÍA ');
INSERT INTO responsabilidad(nombre) VALUES ('SISTEMAS');
INSERT INTO responsabilidad(nombre) VALUES ('SISTEMAS MOB');
INSERT INTO responsabilidad(nombre) VALUES ('SRIA. JA Y MAYORDOMÍA');
INSERT INTO responsabilidad(nombre) VALUES ('SRIA. MIPES - EVANG.- ESC. SAB. - ASA');
INSERT INTO responsabilidad(nombre) VALUES ('SRIA. PUBLIC. Y MN-MA-MM');
INSERT INTO responsabilidad(nombre) VALUES ('TARIJA - BERMEJO');
INSERT INTO responsabilidad(nombre) VALUES ('TARIJA - CENTRAL');
INSERT INTO responsabilidad(nombre) VALUES ('TARIJA - LOMA LINDA');
INSERT INTO responsabilidad(nombre) VALUES ('TÉCNICO AUDIO');
INSERT INTO responsabilidad(nombre) VALUES ('TÉCNICO SECRETARÍA GENERAL');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO - MISIÓN GLOBAL');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO ASISENTE MOB');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO ASISTENTE');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO ASISTENTE ASEA');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO ASISTENTE ASEA-MBC');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO ASISTENTE DE IGLESIA');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO ASISTENTE SISTEMA EDUCATIVO');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO MOB');
INSERT INTO responsabilidad(nombre) VALUES ('TESORERO, MISIÓN GLOBAL');
INSERT INTO responsabilidad(nombre) VALUES ('TRANSMISIÓN');
INSERT INTO responsabilidad(nombre) VALUES ('TRINIDAD NORTE');
INSERT INTO responsabilidad(nombre) VALUES ('TRINIDAD SURESTE');
INSERT INTO responsabilidad(nombre) VALUES ('TRINIDAD SUROESTE');
INSERT INTO responsabilidad(nombre) VALUES ('VENTAS ');
INSERT INTO responsabilidad(nombre) VALUES ('VICE-PRECEPTOR HOGAR DE VARONES');
INSERT INTO responsabilidad(nombre) VALUES ('VICERRECTOR ACADÉMICO');
INSERT INTO responsabilidad(nombre) VALUES ('VICERRECTORA ADMINISTRATIVA FINANCIERA');
INSERT INTO responsabilidad(nombre) VALUES ('VILLAMONTES');
INSERT INTO responsabilidad(nombre) VALUES ('WARNES');
INSERT INTO responsabilidad(nombre) VALUES ('YACUIBA A');
INSERT INTO responsabilidad(nombre) VALUES ('YACUIBA B');
INSERT INTO responsabilidad(nombre) VALUES ('YAPACANI');

-- tipo empleado
INSERT INTO tipoempleado(nombre) VALUES ('OBREROS DE OFICINA');
INSERT INTO tipoempleado(nombre) VALUES ('EMPLEADOS DE OFICINA');
INSERT INTO tipoempleado(nombre) VALUES ('IATEC – UB');
INSERT INTO tipoempleado(nombre) VALUES ('SPA');
INSERT INTO tipoempleado(nombre) VALUES ('UNIDAD EDUCATIVA ADVENTISTA DE BOLIVIA');


-- Contacto UB
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,225,'Adonirám','','Alomía','','','M','2015-02-04','245','','adoniram.alomia@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,33,'Efraín','','Chooue','','','M','1960-04-03','239','','efrain.choque@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,262,'María','','Contreras','','Vela','F','2019-10-17','223','','maria.contreras@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,212,'Jeanete','','Lima','','De souza','F','2015-03-07','242','','jeanete.lima@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,276,'Luis mário','','De souza','','','M','2025-07-15','236','58101','luis.mario@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,8,'Javier','','Guerrero','','','M','1973-05-05','237','','javier.guerrero@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,371,'Amasías','','Lucas','','','M','2014-03-15','','','','amasiaslucas@hotmail.com');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,368,'César','','Mena','','','M','2018-12-17','227','','cesar.mena@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,255,'Andreia','','Giménez','','Mendizábal','F','1969-12-31','247','','andreia.gimenez@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,374,'Henrry','','Mendizábal','','','M','1977-06-06','235','58102','henrry.mendizabal@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,353,'Huáscar','','Parada','','','M','1969-12-31','234','58103','huascar.parada@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,229,'Waldhemir','','Ríos','','','M','2020-04-15','232','58110','waldhemir.rios@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,58,'Alfredo','','Santa cruz','','','M','2015-10-05','222','','alfredo.santacruz@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,1,372,'Carlos','','Zurita','','','M','2015-05-15','226','','carlos.zurita@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,48,'Carla','','Aguirre','','','F','1988-02-11','244','','carla.aguirre@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,55,'Adelaida','','Aruquipa','','','F','1969-12-31','','','','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,355,'Moisés','','Calle','','','M','2015-05-11','232','','moises.calle@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,17,'Guillermo','','Cartagena','','','M','2013-06-15','','','guillermo.cartagena@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,30,'Mariana','','Claure','','','F','1989-10-05','233','','mariana.claure@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,355,'Eloy','Javier','Fernández','','','M','2016-09-15','232','','javier.fernandez@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,7,'José luis','','Mamani','','','M','2019-10-15','243','','jose.mamani@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,244,'Flora','','Martínez','','','F','1969-12-31','','','','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,40,'Vivian','','Mendoza','','','F','2024-11-15','','','vivian.mendoza@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,327,'Rosa','','Nacif','','','F','2015-03-03','249','','rosa.nacif@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,39,'David','','Narvaez','','','M','1980-11-07','','','david.narvaez@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,288,'Vivianna','','Vergara','','Olivares','F','2025-05-15','221','58100','vivianna.vergara@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,335,'Martha','','Ribera','','','F','2028-01-15','246','','martha.ribera@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,333,'Ruth','','Pairo','','Ríos','F','1969-12-31','241','','ruth.pairo@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,268,'Jéssica','','Rodríguez','','','F','1994-04-08','','','jessica.rodriguez@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,244,'Donata','','Silvestre','','Ayala','F','2015-04-02','','','','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,71,'Patricia','','Solís','','Narvaez','F','2019-09-15','225','','patricia.solis@adventistas.org.bo','psolisbolivia@gmail.com');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,59,'Valerio','','Tancara','','','M','2015-09-12','','','','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,355,'René','','Vásquez','','','M','2026-04-15','232','','rene.vasquez@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,55,'Juanita','','Vega','','','F','1969-12-31','','','','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,40,'Shirley','','Villca','','','F','2015-01-01','','','shirley.villca@adventistas.org.bo','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (1,2,344,'Gilvia','','Vivas','','Choque','F','1969-12-31','238','','gilvia.vivas@adventistas.org.bo','');


-- contacto IATEC

INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'David','','Blanco','','','M','2015-09-06','','','david.blanco@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Rodrigo','','Calderón','','','M','2015-10-26','','','rodrigo.calderon@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Jhony','','Calle','','','M','2015-12-12','','','jhony.calle@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Orlando','','Cari','','','M','2015-04-01','','','orlando.cari@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Samuel','','Cari','','','M','1990-04-15','','','samuel.cari@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Ronny','','Castillo','','','M','2015-04-12','','','rony.castillo@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Héctor','','Copa','','','M','1982-09-21','','','hector.copa@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,295,'Josias','','Giménez','','','M','1985-01-18','','','josias.gimenez@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Cristhian','','Jiménez','','','M','2015-04-02','','','cristhian.jimenez@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Jonathan','','Jiménez','','','M','2015-09-04','','','jonathan.jimenez@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Denner','','Llanos','','','M','2015-07-24','','','denner.llanos@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,94,'Roberto','','Ontiveros','','','M','2015-04-12','','','roberto.ontiveros@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Abel','','Ortiz','','','M','2015-10-08','','','abel.ortiz@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Moisés','','Rodríguez','','','M','2015-03-12','','','moises.rodriguez@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Alex','','Salazar','','','M','2015-06-01','','','alex.salazar@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Amed','','Tancara','','','M','2015-08-30','','','amed.tancara@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Adalid','','Flores','','','M','1990-03-27','','','adalid.flores@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Marco antonio','','Aguilar','','','M','1989-10-21','','','marco.aguilar@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Luis fernando','','Poma','','','M','1992-04-26','','','luis.poma@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Osvaldo','','Rodriguez','','','M','1988-07-31','','','osvaldo.rodriguez@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Ronald','','Luna','','','M','1990-12-09','','','ronald.luna@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Isabel','Rosmery','Barja','','','F','1991-12-01','','','rosmery.barja@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Héctor','','Vélez','','','M','2015-03-01','','','hector.velez@adventistas.org','');
INSERT INTO contacto(idDepartamentoContacto,idTipoEmpleado,idResponsabilidad,primerNombre,segundoNombre,apellidoPaterno,apellidoMaterno,apellidoCasada,sexo,fechaNacimiento,interno,voip,emailInstitucional,emailPersonal) VALUES (2,3,280,'Judith','','Villanueva','','','F','2015-09-27','','','judith.villanueva@adventistas.org','');


-- TelefonoContacto
-- telefonos UB
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (1,'Celular','722-37470');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (2,'Celular','722-37033');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (3,'Celular','722-37003');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (4,'Celular','722-37771');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (5,'Celular','722-37020');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (6,'Celular','722-37025');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (7,'Celular','717-37675');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (8,'Celular','722-37702');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (9,'Celular','716-04909');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (10,'Celular','722-72735');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (11,'Celular','721-37708');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (12,'Celular','670-04392');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (13,'Celular','716-55867');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (14,'Celular','727-05999');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (15,'Celular','722-37461');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (16,'Celular','717-30407');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (17,'Celular','717-37656');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (18,'Celular','722-37500');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (19,'Celular','717-29923');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (20,'Celular','722-37779');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (21,'Celular','722-37473');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (22,'','');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (23,'Celular','722-37214');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (24,'Celular','722-37261');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (25,'Celular','707-20297');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (26,'Celular','674-07668');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (27,'Celular','722-02108');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (28,'Celular','717-90796');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (29,'Celular','717-90793');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (30,'Celular','717-30432');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (31,'Celular','722-37778');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (32,'Celular','722-37211');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (33,'Celular','717-37204');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (34,'Celular','717-30409');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (35,'Celular','722-39935');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (36,'Celular','722-00008');
-- telefonos IATEC
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (37,'Celular','717-37502');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (38,'Celular','722-37465');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (39,'Celular','722-37251');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (40,'Celular','722-37742');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (41,'Celular','974-30390');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (42,'Celular','722-37743');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (43,'Celular','678-44833');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (44,'Celular','717-31778');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (45,'Celular','722-37468');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (46,'Celular','722-37718');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (47,'Celular','722-37502');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (48,'Celular','721-37118');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (49,'Celular','722-37464');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (50,'Celular','714-40460');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (51,'Celular','717-37221');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (52,'Celular','722-37467');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (53,'Celular','717-37367');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (54,'Celular','717-29655');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (55,'Celular','717-31390');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (56,'Celular','717-31386');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (57,'Celular','717-31275');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (58,'Celular','717-31398');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (59,'Celular','717-37776');
INSERT INTO telefonocontacto(idContacto,tipoTelefono,numero) VALUES (60,'Celular','722-37501');




